name: ci

on: [push]

jobs:
  test:
5    runs-on: ubuntu-latest
6    steps:
7      - uses: actions/checkout@v2
8      - name: Setup Node.js
9        uses: actions/setup-node@v1
10        with:
11          node-version: "16"
12
13      # Speed up subsequent runs with caching
14      - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"

        - uses: actions/cache@v3
            id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
            with:
              path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
      ${{ runner.os }}-yarn-
26
27      # Install required deps for action
28      - name: Install Dependencies
29        run: yarn
30
31      # Finally, run our tests
32      - name: Run the tests
33        run: yarn test
#   wait_for_vercel:
#     name: Wait for vercel
#     runs-on: ubuntu-latest
#     outputs:
#       preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
#     steps:
#       - name: Wait for Vercel preview deployment to be ready
#         uses: patrickedqvist/wait-for-vercel-preview@main
#         id: waitForVercelPreviewDeployment
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           max_timeout: 120
# pa11y:
#   name: Accessibility tests
#   needs: wait_for_vercel
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 14.x
#     - run: npm install -g pa11y-ci
#     - run: pa11y-ci --sitemap ${{ needs.wait_for_vercel.outputs.preview_url }}/sitemap-0.xml
